name: actions

on:
  workflow_call:

jobs:
  delete_backups:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Delete files
        run: |
          folder='.backups/'
          for file in "$folder"/*; do
            if [ -f "$file" ]; then
              rm "$file"
            fi
          done
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Deleted files in '$folder'"
          git push origin $GITHUB_REF