name: aws

on:
  workflow_dispatch:
      inputs:
        list-bucket:
          description: Do you want to list all object from S3 bucket ?
          required: false
          default: false
          type: boolean
  workflow_call:

jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      # pull the source code
      - uses: actions/checkout@v3

      # configure crendentials for terraform init (state bucket + dynamodb access)
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # verify identity
      - name: verify identity
        run: aws sts get-caller-identity
        shell: bash

      # list backups files on aws
      - name: upload all sql files to s3 bucket
        id: list
        run: aws s3 ls ${{ secrets.AWS_S3_BUCKET_BACKUP }}
        shell: bash

      # run our custom summary script to generate the clickable output
      - name: save output to summary
        if: steps.id.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: >
            require('./.github/summary.js')(require)