name: list aws backups
run-name: list aws backups

on:
  pull_request:
    branches:
      - main
      - ops
      
jobs:
  test:
    uses: ./.github/workflows/test.yml

  backup:
    uses: ./.github/workflows/aws.yml
    needs: [test]
    secrets: inherit