name: List AWS S3 backups manually
run-name: List AWS S3 backups manually

on:
  workflow_dispatch:
    inputs:
      list-bucket:
        description: Do you want to list all object from S3 bucket ?
        required: false
        type: choice
        options:
        - run list
        - cancel

jobs:
  test:
    uses: ./.github/workflows/test.yml

  backup:
    uses: ./.github/workflows/aws.yml
    with:
      env-name: manual-list
      list-bucket: ${{ inputs.list-bucket }}