name: List AWS S3 backups manually
run-name: list aws backups manually

on:
  workflow_dispatch:
    inputs:
      list-bucket:
        description: List all object from S3 bucket
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  backup:
    uses: ./.github/workflows/aws.yml
    secrets: inherit
    with:
      env-name: manual-list
      list-bucket: ${{ inputs.list-bucket }}